name: rydar_app
description: "Rydar guest-only ride tracking MVP."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_tts: ^4.2.3
  geolocator: ^14.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  mapbox_maps_flutter: ^2.12.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/app_icon.png
