// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqMvILLeEO4kfZsN_3yGrgMHVapYZvo8',
    appId: '1:922153097833:web:486f3f40472f58e20320f8',
    messagingSenderId: '922153097833',
    projectId: 'rydarapp-61b0c',
    authDomain: 'rydarapp-61b0c.firebaseapp.com',
    storageBucket: 'rydarapp-61b0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4UY5XyophQSY6oHHp36cDxiCeVLSP1fk',
    appId: '1:922153097833:android:d1bf519095b180560320f8',
    messagingSenderId: '922153097833',
    projectId: 'rydarapp-61b0c',
    storageBucket: 'rydarapp-61b0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBffF3dWaPh7i5AM9eHxTcU-LF5H5Kqb3k',
    appId: '1:922153097833:ios:159a31203ab20af00320f8',
    messagingSenderId: '922153097833',
    projectId: 'rydarapp-61b0c',
    storageBucket: 'rydarapp-61b0c.firebasestorage.app',
    iosBundleId: 'com.example.rydarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBffF3dWaPh7i5AM9eHxTcU-LF5H5Kqb3k',
    appId: '1:922153097833:ios:159a31203ab20af00320f8',
    messagingSenderId: '922153097833',
    projectId: 'rydarapp-61b0c',
    storageBucket: 'rydarapp-61b0c.firebasestorage.app',
    iosBundleId: 'com.example.rydarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfqMvILLeEO4kfZsN_3yGrgMHVapYZvo8',
    appId: '1:922153097833:web:597085cdeba476ec0320f8',
    messagingSenderId: '922153097833',
    projectId: 'rydarapp-61b0c',
    authDomain: 'rydarapp-61b0c.firebaseapp.com',
    storageBucket: 'rydarapp-61b0c.firebasestorage.app',
  );
}
